### PR TITLE
Fail boot if we have an MBOXv1 daemon

### PR DESCRIPTION
**Pull request by wak-google**
The reference mbox v1 daemon causes corruption when performing
partial writes. The current daemon is mbox v2+ and any non-reference
daemon should implement at least mbox v2. Failing loudly on encountering the
old type of daemon will prevent headaches for users accidentally using
old versions.

Change-Id: Ic19ef67509ab58bdaf8d4b816035b4ebf12fc37d
Signed-off-by: William A. Kennington III <wak@google.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/hostboot/105)

### CODE REVIEW

**Comment by cyrilbur-ibm** [comment]
Hi William,

Yes, ultimately this is a good idea. I'm torn about not letting the machine boot however, the easiest upgrade path for a lot of machines is from the host. It might be wise to still allow the box to limp along if only so that all components can be updated to at least v2.

**Comment by wak-google** [comment]
Sure, but you will only get a single boot. Upon booting the second time the machine will already be bricked. It's my understanding that no one using an old enough BMC to have mbox v1 can flash the BMC from the host anyway, without having an out of band way to flash the BMC. As soon as the BMC is updated the host side would be able to boot.

**Comment by cyrilbur-ibm** [comment]
Sorry I wasn't aware that the v1 bug would cause corruption just from booting. We've only ever seen the bug cause corruption through updating flash by nvram. Although I won't deny it is possible.
The way I see it, either way we're preventing the host from booting. Either by refusing to boot or by allowing the boot to go ahead and risking corruption. If the user gets unlucky then the flash will get corrupted and they won't boot which puts them in the same position as if they had this patch. Why not give them the chance?

**Comment by sjitindarsingh** [comment]
There are V1 implementations out there which, to the best of my knowledge, work completely fine and don't corrupt the flash when writing to it. I don't think it's correct to fail the boot if we were to encounter one of these implementations.

At best you might want to provide a warning to the user that writing to the flash has the potential to cause corruption (normally caused when erase and block size differ or partitions aren't aligned). But completely terminating the boot is the wrong approach in my opinion.

**Comment by dcrowell77** [comment]
@wghoffa @sannerd 
Does anyone have visibility on the current status of the non-OpenBMC implementations?

**Comment by wghoffa** [comment]
The SuperMicro BMC has moved up to V2. Trying to check on AMI still.

**Comment by wghoffa** [comment]
It appears AMI doesn't have mbox support functional yet. Those are the only BMC vendors I know about @dcrowell77 .

**Comment by wak-google** [comment]
It sounds like this won't work for all MBOX daemons so lets ignore this one.

**Pull request closed without merging**
