### PR TITLE
IPMI Watchdog Cleanups

### PR DESCRIPTION
**Pull request by wak-google**
Improve our watchdog coverage during the hostboot process and during the transition into OPAL firmware.

### CODE REVIEW

**Comment by dcrowell77** [comment]
@stewart-ibm - Can you confirm OPAL is ready to handle the change to enable the watchdog when we transition?

**Comment by dcrowell77** [comment]
> a time skiboot is not the payload ... IPMI enabled hostboot

Nothing that is officially supported right now on P9.  One could theoretically start up anything, e.g. bare-metal linux, a test executable, etc.  There have been (and will be) PHYP-enabled BMC-based systems, but in that case PHYP would have the same requirements as skiboot/opal.

**Comment by wak-google** [comment]
ping @stewart-ibm

**Comment by dcrowell77** [comment]
All of our CIs have passed so I'm pushing this in

**Pull request closed without merging**
