### PR TITLE
fix chip unit mask error for nmmu1 PartialGoodRule

### PR DESCRIPTION
**Pull request by lili-lilili**

### CODE REVIEW

**Comment by dcrowell77** [comment]
Good catch, we'll take a look and get the change in.

**Comment by dcrowell77** [comment]
I'm curious, how did you discover this bug?  As far as I'm aware, there are no shipping parts with the NMMU1 marked as bad.

**Comment by lili-lilili** [comment]
> I'm curious, how did you discover this bug? As far as I'm aware, there are no shipping parts with the NMMU1 marked as bad.

We are testing opal on  the rainier.
When we test  ioSCM cpu, the nmmu1 config always report error.
I want to confirm if nmmu1 is being discovered and initialized correct.
So I check the PG keyword in the mvpd and the PG rule for the nmmu1, then the problem is found.

Now I know the nmmu1 is deconfiged,  but this is still a problem to opal.
Because Hostboot does not pass the functional status of nmmu to OPAL, OPAL does not know which nmmu is available. 
Can you give me some advice?

**Comment by dcrowell77** [comment]
Full opencapi support is one of the features that hasn't been done in our P10 product code so I'm not surprised there are still some holes.  At a high level, the way it should be working is that the SMP Link Entry Information area of HDAT should be filled in with accurate data for the links that are currently active.  OPAL would then consume that data to decide which links to train.

Note that there is currently nothing in IBM's plans to implement this support.

**Comment by lili-lilili** [comment]
> Full opencapi support is one of the features that hasn't been done in our P10 product code so I'm not surprised there are still some holes. At a high level, the way it should be working is that the SMP Link Entry Information area of HDAT should be filled in with accurate data for the links that are currently active. OPAL would then consume that data to decide which links to train.
> 
> Note that there is currently nothing in IBM's plans to implement this support.

I think we can do this job;.
I will create another pull request.
I hope you can help to check and merge the request.

**Comment by dcrowell77** [comment]
Sounds great.  This current PR is just going through the internal testing/review process, it should be in soon.

**Pull request closed without merging**
